WebApplication1/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;

namespace WebApplication1.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        public DbSet<Player> Players { get; set; }
        public DbSet<Team> Teams { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<Player>()
                .Property(p => p.Gender)
                .HasConversion(
                    v => v.ToString(),
                    v => (Gender)Enum.Parse(typeof(Gender), v));

            modelBuilder
                .Entity<Player>()
                .Property(p => p.Country)
                .HasConversion(
                    v => v.ToString(),
                    v => (Country)Enum.Parse(typeof(Country), v));
        }
    }
}

WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Player
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public Gender Gender { get; set; }
        [Required]
        [RegularExpression(@"\d{2}/\d{2}/\d{4}", ErrorMessage = "Неправильный формат")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public string Birth { get; set; }
        [Required]
        [Display(Name = "Team")]
        public int TeamId { get; set; }
        public Team Team { get; set; }
        [Required]
        public Country Country { get; set; }
    }

    public enum Gender
    {
        Male,
        Female
    }

    public enum Country
    {
        Russia,
        USA,
        Italy
    }
}

WebApplication1/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Team
    {
        [Key]
        public int TeamId { get; set; }
        [Required]
        public string Name { get; set; }
        public List<Player> Players { get; set; }
    }
}

WebApplication1/Controllers/PlayersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Hubs;
using Microsoft.AspNetCore.SignalR;

namespace WebApplication1.Controllers
{
    public class PlayersController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHubContext<ChatHub> _hub;
        [BindProperty]
        public Player Player { get; set; }
        [BindProperty]
        public Player Team { get; set; }
        public PlayersController(ApplicationDbContext db, IHubContext<ChatHub> hub)
        {
            _db = db;
            _hub = hub;
        }
        
        // GET: Players
        public IActionResult Index()
        {
            var players = _db.Players.ToList();
            if (players != null)
            {
                foreach (Player p in players)
                {
                    _db.Teams.Where(t => t.TeamId == p.TeamId).Load();
                }
                return View(players);
            }
            return NotFound();
        }

        public IActionResult Upsert(int? id)
        {
            var teams = _db.Teams.ToList();
            ViewBag.Teams = new SelectList(teams, "TeamId", "Name");

            // create
            if (id == null)
            {
                Player = new Player();
                return View(Player);
            }
            // update
            Player = _db.Players.FirstOrDefault(u => u.Id == id);
            if (Player == null)
            {
                return NotFound();
            }
            return View(Player);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert()
        {
            if (ModelState.IsValid)
            {
                if (Player.Id == 0)
                {
                    //create
                    _db.Players.Add(Player);
                }
                else
                {
                    _db.Players.Update(Player);
                }
                _db.SaveChanges();

                string id = Player.Id.ToString();
                string name = Player.Name;
                string surname = Player.Surname;
                string birth = Player.Birth;
                string team = _db.Teams.FirstOrDefault(t => t.TeamId == Player.TeamId).Name;
                string gender = Player.Gender.ToString();
                string country = Player.Country.ToString();

                // Пытался отрендерить партиал GetPlayer и отдать в SendAsync как строку,
                // но не нашел как рендерить html в строку

                await _hub.Clients.All.SendAsync("ReceiveMessage", id, name, surname, birth, team, gender, country);
                return RedirectToAction("Index");
            }
            return View(Player);
        }
    }
}

WebApplication1/Controllers/TeamsController.cs
using System;
using System.Linq;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Team Team { get; set; }
        public TeamsController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: Teams
        public ActionResult Index()
        {

            var teams = _db.Teams.ToList();
            if (teams != null)
            {
                foreach (Team t in teams)
                {
                    _db.Players.Where(p => p.TeamId == t.TeamId).Load();
                }
                return View(teams);
            }
            return NotFound();
        }

        // POST: Teams/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromBody] Team team)
        {
            string name = team.Name.Trim();
            if (!String.IsNullOrWhiteSpace(name) || !String.IsNullOrEmpty(name))
            {
                if (_db.Teams.FirstOrDefault(p => p.Name == name) == null)
                {
                    _db.Teams.Add(team);
                    _db.SaveChanges();
                    return new JsonResult(team);
                }
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return new JsonResult("Team is exists");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return new JsonResult(string.Join(";", ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage)));
        }
    }
}

WebApplication1/Views/Players/Index.cshtml
@model IEnumerable<Player>

<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Список футболистов</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Players" class="btn btn-info form-control text-white">
            Добавить нового футболиста
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="PlayersList" class="table table-striped table-bordered" style="width:100%">
            @if (Model.Count() > 0)
            {
                <thead>
                    <tr class="text-center">
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Пол</th>
                        <th>Дата рождения</th>
                        <th>Команда</th>
                        <th>Страна</th>
                        <th>Опция</th>
                    </tr>
                </thead>
                @await Html.PartialAsync("_GetPlayer", Model)
            }
            else
            {
                <tr>Пока никаких футболистов не добавлено.</tr>
            }
        </table>
    </div>
</div>

WebApplication1/Views/Players/Upsert.cshtml
@{
    ViewData["Title"] = "Upsert";
}

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf

@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}

@model WebApplication1.Models.Player

<br />
<h2 class="text-info">@(Model.Id != 0 ? "Редактировать данные" : "Добавить") Футболиста</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Name">Имя</label>
            </div>
            <div class="col-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Surname">Фамилия</label>
            </div>
            <div class="col-6">
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Gender">Пол</label>
            </div>
            <div class="col-6">
                <select asp-for="Gender" asp-items="@new SelectList(Enum.GetNames(typeof(Gender)))" class="form-control"></select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Birth">Дата рождения</label>
            </div>
            <div class="col-6">
                <input asp-for="Birth" class="form-control" />
                <span asp-validation-for="Birth" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="TeamId">Команда</label>
            </div>
            <div class="col-6">
                <select asp-for="TeamId" asp-items="ViewBag.teams" class="form-control"></select>
                <span asp-validation-for="TeamId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label>Создать команду</label>
            </div>
            <div class="col-6">
                <input id="TeamName" class="form-control" name="TeamName" value="" />
                <input type="button" class="btn btn-primary form-control" value="Создать" id="buttonTeam">
                <span class="text-danger field-validation-valid" id="TeamError"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Country"></label>
            </div>
            <div class="col-6">
                <select asp-for="Country" asp-items="@new SelectList(Enum.GetNames(typeof(Country)))" class="form-control"></select>
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" id="UpsetButton" class="btn btn-primary form-control">
                    @(Model.Id != 0 ? "Обновить" : "Создать")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Возврат к списку</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            // Flatpickr
            $('#Birth').flatpickr({ dateFormat: 'd/m/Y', maxDate: "today" })
            // Ajax create Team
            $('#buttonTeam').click(function () {
                var teamError = document.getElementById('TeamError');
                var teamName = document.getElementById('TeamName');
                var teamSelect = document.getElementById('TeamId');

                var data = { name: teamName.value }

                $.ajax({
                    url: '@Url.Action("Create","Teams")',
                    type: 'post',
                    contentType: 'application/json',
                    dataType: "JSON",
                    headers:
                    {
                        "RequestVerificationToken": '@GetAntiXsrfRequestToken()'
                    },
                    data: JSON.stringify(data),
                    success: function (result) {
                        console.log(result);
                        console.log(result.name);
                        console.log(result.teamId);
                        var option = document.createElement('option');
                        option.innerText = result.name;
                        option.value = result.teamId;
                        option.setAttribute('value', result.teamId);
                        option.selected = true;
                        teamSelect.insertAdjacentElement('afterbegin', option);
                        teamError.innerHTML = '';
                        teamName.value = '';
                    },
                    error: function (xhr) {
                        var errorData = $.parseJSON(xhr.responseText);
                        teamError.innerHTML = errorData;
                    }
                });
            });
        });
    </script>
}

WebApplication1/Views/Players/_GetPlayer.cshtml
@model IEnumerable<Player>

@foreach (Player p in Model)
{
    <tr id="@p.Id" class="text-center">
        <td class="1">@p.Name</td>
        <td class="2">@p.Surname</td>
        <td class="3">@p.Gender</td>
        <td class="4">@p.Birth</td>
        <td class="5">@p.Team?.Name</td>
        <td class="6">@p.Country</td>
        <td>
            <a asp-action="Upsert" asp-route-id="@p.Id" asp-controller="Players" class="btn btn-outline-dark form-control">
                Редактировать
            </a>
        </td>
    </tr>
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Тест 66 бит</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Players" asp-action="Index">Менеджер футбольных команд</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Футболисты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Upsert">Добавить футболиста</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Команды</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
    <script>
        "use strict"

        var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();

        connection.on("ReceiveMessage", function (player) {
            var 
            var msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
            var encodedMsg = user + " says " + msg;
            var li = document.createElement("li");
            li.textContent = encodedMsg;
            document.getElementById("messagesList").appendChild(li);
        });
    </script>
  
    @RenderSection("Scripts", required: false)
</body>
</html>